FROM python:3.12

RUN pip install --upgrade pip

RUN useradd -ms /bin/bash admin
USER admin
WORKDIR /home/admin

COPY --chown=admin:admin requirements.txt requirements.txt

ENV PATH="/home/admin/.local/bin:${PATH}"

RUN pip install --user -r requirements.txt

COPY --chown=admin:admin . .

ENTRYPOINT ["sh", "run-worker.sh"]
